global:
  cluster: monitoring

  projects:

    prometheus-app:
      description: 'prometheus deployment'
      sourceRepos:
      - git@github.com:paas2/prometheus.git
      destinations:
        namespaces:
        - monitoring
        - kube-system
      extraFields: |
        clusterResourceWhitelist:
        - group: '*'
          kind: '*' 

    thanos:
      description: 'ad-integration'
      sourceRepos:
      - git@github.com:paas2/ad-integration.git
      destinations:
        namespaces:
        - ad-integration
      extraFields: |
        clusterResourceWhitelist:
        - group: '*'
          kind: '*'           
                              
  applications:
    prometheus-app:
      destination:
        namespace: monitoring
      project: prometheus-app
      source:
        path: helm-charts/kube-prometheus
        repoURL: git@github.com:paas2/prometheus.git   
        extraSourceFields: |
          helm:
            valueFiles:
            - values.yaml   
            - values-{{ $.Values.global.cluster }}-{{ $.Values.global.envName }}.yaml

    thanos:
      destination:
        namespace: ad-integration
      project: thanos
      source:
        path: helm-charts/ad-integration
        repoURL: git@github.com:paas2/ad-integration.git     
        extraSourceFields: |
          helm:
            valueFiles:
            - values.yaml   
            - values-{{ $.Values.global.cluster }}-{{ $.Values.global.envName }}.yaml   
